// Mocks generated by Mockito 5.4.0 from annotations
// in movie_app/test/movie_detail/presentation/controller/tv_detail_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_app/core/failure/failure.dart' as _i5;
import 'package:movie_app/core/result/result.dart' as _i6;
import 'package:movie_app/movie_detail/data/model/cast.dart' as _i8;
import 'package:movie_app/movie_detail/data/model/tv_detail.dart' as _i7;
import 'package:movie_app/movie_detail/data/model/video.dart' as _i9;
import 'package:movie_app/movie_detail/domain/repo/tv_detail_repo.dart' as _i2;

import 'tv_detail_controller_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTvDetailRepo_0 extends _i1.SmartFake implements _i2.TvDetailRepo {
  _FakeTvDetailRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvDetailUsecaseTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvDetailUsecaseTest extends _i1.Mock
    implements _i3.TvDetailUsecaseTest {
  MockTvDetailUsecaseTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvDetailRepo get repo => (super.noSuchMethod(
        Invocation.getter(#repo),
        returnValue: _FakeTvDetailRepo_0(
          this,
          Invocation.getter(#repo),
        ),
      ) as _i2.TvDetailRepo);
  @override
  set repo(_i2.TvDetailRepo? _repo) => super.noSuchMethod(
        Invocation.setter(
          #repo,
          _repo,
        ),
        returnValueForMissingStub: null,
      );
  @override
  dynamic getMovieDetail(
    int? id,
    dynamic Function(_i4.Either<_i5.Failure, _i6.Result<_i7.TvDetail>>)? res,
  ) =>
      super.noSuchMethod(Invocation.method(
        #getMovieDetail,
        [
          id,
          res,
        ],
      ));
  @override
  dynamic getMovieCasts(
    int? id,
    dynamic Function(_i4.Either<_i5.Failure, _i6.Result<List<_i8.Cast>>>)? res,
  ) =>
      super.noSuchMethod(Invocation.method(
        #getMovieCasts,
        [
          id,
          res,
        ],
      ));
  @override
  dynamic getMovieVideos(
    int? id,
    dynamic Function(_i4.Either<_i5.Failure, _i6.Result<List<_i9.Video>>>)? res,
  ) =>
      super.noSuchMethod(Invocation.method(
        #getMovieVideos,
        [
          id,
          res,
        ],
      ));
}
