// Mocks generated by Mockito 5.4.0 from annotations
// in movie_app/test/home/presentation/controller/home_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_app/core/data_model/movei_list_item_model.dart' as _i7;
import 'package:movie_app/core/failure/failure.dart' as _i5;
import 'package:movie_app/core/result/result.dart' as _i6;
import 'package:movie_app/home/domain/repo/home_repository.dart' as _i2;
import 'package:movie_app/movie_detail/data/model/cast.dart' as _i9;
import 'package:movie_app/movie_detail/data/model/movie_detail.dart' as _i8;
import 'package:movie_app/movie_detail/data/model/video.dart' as _i10;

import 'home_controller_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHomeRepository_0 extends _i1.SmartFake
    implements _i2.HomeRepository {
  _FakeHomeRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeCategoryUsecaseTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeCategoryUsecaseTest extends _i1.Mock
    implements _i3.HomeCategoryUsecaseTest {
  MockHomeCategoryUsecaseTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repo => (super.noSuchMethod(
        Invocation.getter(#repo),
        returnValue: _FakeHomeRepository_0(
          this,
          Invocation.getter(#repo),
        ),
      ) as _i2.HomeRepository);
  @override
  set repo(_i2.HomeRepository? _repo) => super.noSuchMethod(
        Invocation.setter(
          #repo,
          _repo,
        ),
        returnValueForMissingStub: null,
      );
  @override
  dynamic getMovieCategory(
    int? page,
    String? type,
    dynamic Function(
            _i4.Either<_i5.Failure, _i6.Result<List<_i7.MovieListItemModel>>>)?
        res,
  ) =>
      super.noSuchMethod(Invocation.method(
        #getMovieCategory,
        [
          page,
          type,
          res,
        ],
      ));
}

/// A class which mocks [MovieDetailUsecaseTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailUsecaseTest extends _i1.Mock
    implements _i3.MovieDetailUsecaseTest {
  MockMovieDetailUsecaseTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  dynamic getMovieDetail(
    int? id,
    dynamic Function(_i4.Either<_i5.Failure, _i6.Result<_i8.MovieDetail>>)? res,
  ) =>
      super.noSuchMethod(Invocation.method(
        #getMovieDetail,
        [
          id,
          res,
        ],
      ));
  @override
  dynamic getMovieCasts(
    int? id,
    dynamic Function(_i4.Either<_i5.Failure, _i6.Result<List<_i9.Cast>>>)? res,
  ) =>
      super.noSuchMethod(Invocation.method(
        #getMovieCasts,
        [
          id,
          res,
        ],
      ));
  @override
  dynamic getMovieVideos(
    int? id,
    dynamic Function(_i4.Either<_i5.Failure, _i6.Result<List<_i10.Video>>>)?
        res,
  ) =>
      super.noSuchMethod(Invocation.method(
        #getMovieVideos,
        [
          id,
          res,
        ],
      ));
}
