// Mocks generated by Mockito 5.4.0 from annotations
// in movie_app/test/movies/presentation/controllers/movie_list_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_app/core/data_model/movei_list_item_model.dart' as _i7;
import 'package:movie_app/core/failure/failure.dart' as _i5;
import 'package:movie_app/core/result/result.dart' as _i6;
import 'package:movie_app/movies/domain/repository/movie_list_repository.dart'
    as _i2;

import 'movie_list_controller_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMovieListRepository_0 extends _i1.SmartFake
    implements _i2.MovieListRepository {
  _FakeMovieListRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovieListUsecaseTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieListUsecaseTest extends _i1.Mock
    implements _i3.MovieListUsecaseTest {
  MockMovieListUsecaseTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieListRepository get repo => (super.noSuchMethod(
        Invocation.getter(#repo),
        returnValue: _FakeMovieListRepository_0(
          this,
          Invocation.getter(#repo),
        ),
      ) as _i2.MovieListRepository);
  @override
  set repo(_i2.MovieListRepository? _repo) => super.noSuchMethod(
        Invocation.setter(
          #repo,
          _repo,
        ),
        returnValueForMissingStub: null,
      );
  @override
  dynamic getMovies(
    int? page,
    dynamic Function(
            _i4.Either<_i5.Failure, _i6.Result<List<_i7.MovieListItemModel>>>)?
        res,
  ) =>
      super.noSuchMethod(Invocation.method(
        #getMovies,
        [
          page,
          res,
        ],
      ));
}
